#pragma once
#ifdef JUEGO_EXPORTS
#define JUEGO_API __declspec(dllexport)
#else
#define JUEGO_API __declspec(dllimport)
#endif

// FUNCIÓN PRINCIPAL PARA CARGAR EL JUEGO: ES LLAMADA DESDE EL MOTOR PARA LANZARLO
// LOS JUEGOS NECESITARÁN ESTA FUNCION OBLIGATORIAMENTE PARA QUE EL MOTOR PUEDA LLAMAR A LA LIBRERÍA DINÁMICA
extern "C" JUEGO_API int LoadGame();
